# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  vaportrail-benchmarks:
    dependencies:
    - base
    - vaportrail
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: vaportrail is a new Haskeleton package.
executables:
  vaportrail:
    dependencies:
    - base
    - vaportrail
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/vaportrail
library:
  dependencies:
  - base
  - bytestring
  - split
  - machines
  - vector
  source-dirs: library
license: GPLv2
maintainer: Author name here
name: vaportrail
synopsis: A new Haskeleton package.
tests:
  vaportrail-test-suite:
    dependencies:
    - base
    - vaportrail
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
