# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  vaportrail-benchmarks:
    dependencies:
    - base
    - vaportrail
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: vaportrail is a tool for data transmission over FM with a Raspberry Pi and RTL_SDR
executables:
  vaportrail:
    dependencies:
    - base
    - vaportrail
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: inguardians/vaportrail
library:
  dependencies:
  - base
  - binary
  - bytestring
  - cryptonite
  - fec
  - ghc-prim
  - lens
  - memory
  - random
  - reflection
  - split
  - vector
  - filepath
  - directory
  - async
  - tar
  - process
  - fsnotify
  - stm
  - mtl
  source-dirs: library
license: GPLv2
maintainer: Galen Alderson
name: vaportrail
synopsis: vaportrail is a tool for data transmission over FM with a Raspberry Pi and RTL_SDR
tests:
  vaportrail-test-suite:
    dependencies:
    - base
    - vaportrail
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.1.0'
